### PR TITLE
change sha-256 in the assetlink.json

### PR DESCRIPTION
**Pull request by chheanpisethpanha**
Last time, I got the wrong sha certificate. I replaced it with the correct one, that google provided. Can I have it live on the main website?

https://vkirirom.com/.well-known/assetlinks.json

### CODE REVIEW

**Comment by mort3za** [comment]
@chheanpisethpanha PR has a conflict in the json file.

**Comment by chheanpisethpanha** [comment]
@mort3za i resolved the conflict now can you check?

**Comment by paulchrisluke** [comment]
@chheanpisethpanha We are finally getting around to getting our licensing squared away, since you've contributed before, would you mind agreeing to our opensource use of your code? https://hub.paulchrisluke.com/paul-chris-luke-agency-opensource-consent-form

Also, we need similar work done for our opensource app https://foodouken.com . Would you be interested in helping with that?

**Comment by chheanpisethpanha** [comment]
@paulchrisluke can u tell me what kind of work? just wanna know and see if im able to do it or not, regarding time... also my skills!

**Comment by paulchrisluke** [comment]
@chheanpisethpanha its adding foodouken.com to the itunes and google play app store, same thing you did for vkirirom

**Pull request merged**
