### PR TITLE
add swagger-to-axios-codegen package

### PR DESCRIPTION
**Pull request by mort3za**
Add `swagger-to-axios-codegen` package, remove `vue-resource` package, replace all `this.$http` requests with axios requests.
Every time that swagger API gets an update, we should run `npm run swagger`.

### CODE REVIEW

**Comment by mort3za** [comment]
Thank you for the review, sir. Personally prefer async/await where there is no chance of error because I want to avoid try/catch syntax (change my mind if I'm wrong please). Oh, Although I should add `.catch` to those requests later!

**Comment by StrangeWill** [comment]
> change my mind if I'm wrong please

It's less of a right/wrong thing and more of a goal --  The main goal of async/await is to make code more readable from the old promise consumer model, functionally they're the same.

It becomes more of an issue when chaining results and dealing with errors, this project lacks a lot of that which is one reason I've been pretty lax about it, it ultimately matters little here.

Some reading on that:
https://hackernoon.com/6-reasons-why-javascripts-async-await-blows-promises-away-tutorial-c7ec10518dd9

Arguably after playing with this code, things like `byCompanyByCategoryName` should probably take primitives instead of objects -- is there a way to configure the generator to do so?

**Comment by mort3za** [comment]
It gets these names from the swagger API (a json file that have all swagger configs). So we can change them in backend code. I don't know the details but it's certainly possible.

**Comment by atharva3010** [comment]
Looks great now

**Pull request merged**
