### PR TITLE
Minors: footer links, readme, datepicker colors, some texts colors

### PR DESCRIPTION
**Pull request by paulchrisluke**
- Update readme
- Update footer links
- Update datepicker colors

#359
#359
#334

### CODE REVIEW

**Comment by paulchrisluke** [comment]
I just commented out the transition here, that may not fix what I was looking to do here: #370

**Comment by mort3za** [comment]
> I just commented out the transition here, that may not fix what I was looking to do here: #370
Yeah, it's not enough. I did it here #391

**Comment by mort3za** [comment]
@paulchrisluke blog page return 404 in API

**Comment by paulchrisluke** [comment]
@mort3za https://develop.vkirirom.com/search/blog
Added "blog" search page into database

**Pull request merged**
