### PR TITLE
booking dialogs - make submit section sticky

### PR DESCRIPTION
**Pull request by mort3za**
#219

### CODE REVIEW

**Comment by mort3za** [comment]
@paulchrisluke Please check the sticky bar in "Choose Dates" dialog, if that's OK will do this for other dialogs too.

**Comment by paulchrisluke** [comment]
image
can you extend the yellow button to full width and show us again? @mort3za

**Comment by mort3za** [comment]
@paulchrisluke PR updated. I noticed it's not easy to detect the content below the sticky section because it's background is the same as the modal's background. I suggest adding a background like this:

image

**Comment by paulchrisluke** [comment]
The submission buttons are only sticky for "confirm dates", not sticky for "confirm guests" and "confirm booking' in the booking flow in our deploy preview 
https://deploy-preview-290--cranky-nightingale-3731fc.netlify.com/listing/Bell-Tent

Make the button stick for all instances of those booking screens

**Comment by mort3za** [comment]
Sure, what about my suggestion for background? (screenshot above) @paulchrisluke

**Comment by bamboochow** [comment]
image
Add dividers between sections for "choose dates"

**Pull request merged**
