### PR TITLE
Fix: set to 8x8: Fonts, Colors, Footer, Home, Listing page

### PR DESCRIPTION
**Pull request by louisstallardphillips**
Sorry for formatting change, I will turn off my format on save.

### CODE REVIEW

**Comment by mort3za** [comment]
Please provide a full details of the changes, or write the related issue number.
Thank you

**Comment by louisstallardphillips** [comment]
Sorry, I only wrote the issue number #187 on the branch name, I also pulled from master not staging.

**Comment by louisstallardphillips** [comment]
I will redo the commit without my mistakes

**Comment by mort3za** [comment]
That would be nice! :+1:

**Pull request closed without merging**
