### PR TITLE
add assetlinks.json and add redirect to that file

### PR DESCRIPTION
**Pull request by chheanpisethpanha**
_add assetlinks.json and add redirect to that file_
I have made changes in the master branch, so can it be live? @mort3za

### CODE REVIEW

**Comment by mort3za** [comment]
The changes you made are no correct. You can see the similar PR here:
https://github.com/whynotearth/hotel-website-vkirirom.com/pull/262/files

In that PR, put your json file instead of 1.txt

Check the preview link to see if it really works or not.

**Comment by mort3za** [comment]
move your file to assets folder, like that PR and change **from** to point the new address

**Comment by mort3za** [comment]
Sorry, 'static' folder

**Comment by chheanpisethpanha** [comment]
image

It works now, so what's next? @mort3za

**Comment by mort3za** [comment]
@chheanpisethpanha That should work now.

**Pull request merged**
