### PR TITLE
update deps

### PR DESCRIPTION
**Pull request by mort3za**
Created a new project by vue cli 3 and moved source files.
Also minor fixes related to build fixed, and versions became strict in package.json

To start local server now we should run `npm run serve`

### CODE REVIEW

**Comment by mort3za** [comment]
@atharva3010 Please clone again, merge this PR and test functionalities of the website. Changes are massive, maybe there is an issue that I could not see.

**Comment by mort3za** [comment]
package-lock is designed to be shared between developers, we should keep it. @StrangeWill

**Comment by StrangeWill** [comment]
Right, I said set it to a binary file, you do this under `.gitattributes`, it tells git to handle diffs a little different so when you run things like `git diff` you don't get 11k lines of package-lock.json making a bunch of changes that aren't really going to be reviewed.

They still get committed/updated/etc. like normal.

It's a _small_ quality-of-life improvement. Definitely not required as part of this PR, was just a minor note.

**Comment by mort3za** [comment]
@StrangeWill Uh, didn't hear about it, interesting. Thank you for mentioning it.

**Comment by paulchrisluke** [comment]
I did some qa on this and its looking good to me. https://deploy-preview-148--cranky-nightingale-3731fc.netlify.com/Contact

Waiting for @atharva3010 to review and merge after he finishes his changes

**Comment by atharva3010** [comment]
It still has some merge conflicts. Also, the pwa doesn't have our assets.

**Pull request merged**
